/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Google Play Review Analyzer
 * OpenAPI spec version: 0.1.0
 */
import { customInstance } from '.././axios-instance';



  export const getDefault = () => {
/**
 * @summary Health Check
 */
const healthCheckHealthGet = (

 ) => {
      return customInstance<unknown>(
      {url: `/health`, method: 'GET'
    },
      );
    }
  return {}};
