/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Google Play Review Analyzer
 * OpenAPI spec version: 0.1.0
 */
import type {
  FetchAndAnalyzeRequest,
  FetchAndAnalyzeResponse,
  FetchReviewsRequest,
  FetchReviewsResponse
} from '../models';

import { customInstance } from '.././axios-instance';



  export const getReviews = () => {
/**
 * @summary Get Reviews
 */
const getReviewsApiReviewsGet = (

 ) => {
      return customInstance<unknown>(
      {url: `/api/reviews/`, method: 'GET'
    },
      );
    }
  /**
 * @summary Fetch Reviews
 */
const fetchReviewsApiReviewsFetchPost = (
    fetchReviewsRequest: FetchReviewsRequest,
 ) => {
      return customInstance<FetchReviewsResponse>(
      {url: `/api/reviews/fetch`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: fetchReviewsRequest
    },
      );
    }
  /**
 * @summary Fetch And Analyze
 */
const fetchAndAnalyzeApiReviewsFetchAndAnalyzePost = (
    fetchAndAnalyzeRequest: FetchAndAnalyzeRequest,
 ) => {
      return customInstance<FetchAndAnalyzeResponse>(
      {url: `/api/reviews/fetch-and-analyze`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: fetchAndAnalyzeRequest
    },
      );
    }
  return {getReviewsApiReviewsGet,fetchReviewsApiReviewsFetchPost,fetchAndAnalyzeApiReviewsFetchAndAnalyzePost}};
export type GetReviewsApiReviewsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getReviews>['getReviewsApiReviewsGet']>>>
export type FetchReviewsApiReviewsFetchPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getReviews>['fetchReviewsApiReviewsFetchPost']>>>
export type FetchAndAnalyzeApiReviewsFetchAndAnalyzePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getReviews>['fetchAndAnalyzeApiReviewsFetchAndAnalyzePost']>>>
