/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Google Play Review Analyzer
 * OpenAPI spec version: 0.1.0
 */

export type AnalyzedReviewResponsePriority = typeof AnalyzedReviewResponsePriority[keyof typeof AnalyzedReviewResponsePriority];


export const AnalyzedReviewResponsePriority = {
  high: 'high',
  medium: 'medium',
  low: 'low',
} as const;
