/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Google Play Review Analyzer
 * OpenAPI spec version: 0.1.0
 */

export type AnalyzedReviewResponseSentiment = typeof AnalyzedReviewResponseSentiment[keyof typeof AnalyzedReviewResponseSentiment];


export const AnalyzedReviewResponseSentiment = {
  positive: 'positive',
  neutral: 'neutral',
  negative: 'negative',
} as const;
