/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Google Play Review Analyzer
 * OpenAPI spec version: 0.1.0
 */

export interface FetchReviewsRequest {
  /** Full Google Play Store URL */
  url: string;
  /** Sort order: 'newest' or 'relevant' */
  sort?: string;
  /** Filter by star rating (1-5). None means all scores. */
  filter_score?: number | null;
  /** Only include reviews created on or after this date (ISO 8601). */
  since?: string | null;
}
