/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Google Play Review Analyzer
 * OpenAPI spec version: 0.1.0
 */

export interface FetchAndAnalyzeRequest {
  /** Full Google Play Store URL */
  url: string;
  /** Sort order: 'newest' or 'relevant' */
  sort?: string;
  /** Filter by star rating (1-5). None means all scores. */
  filter_score?: number | null;
  /** Only include reviews from this date onwards. */
  since?: string | null;
  /** Optional extra instructions for sentiment analysis. Appended between the task description and the review text. Example: 'Reviews about pricing alone should be neutral, not negative.' */
  sentiment_instructions?: string;
  /** Optional extra instructions for priority classification. Appended between the task description and the review text. Example: 'Pay special attention to crash reports and login issues.' */
  priority_instructions?: string;
}
