/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Google Play Review Analyzer
 * OpenAPI spec version: 0.1.0
 */

export interface GenerateReplyRequest {
  /** Name of the reviewer. */
  user_name: string;
  /** The review text. */
  review_content: string;
  /** Optional extra instructions for reply generation. */
  reply_instructions?: string;
}
