/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Google Play Review Analyzer
 * OpenAPI spec version: 0.1.0
 */

export interface ReviewResponse {
  review_id: string;
  user_name: string;
  user_image: string;
  content: string;
  score: number;
  thumbs_up_count: number;
  review_created_version: string | null;
  at: string;
  reply_content: string | null;
  replied_at: string | null;
  app_version: string | null;
}
